
#pragma once

enum BENCHMARK_TASK_TYPE {
  TASK_PICK_UP = 0,
  TASK_SIMPLE_JOINT = 1,
  TOTAL_TASK_TYPES = 2
};


enum TEST2_STATES {
  SLEEPING = 0,
  LISTENING = 1,
  START_TASK = 2,
  WAIT_INPUT_CLIENT = 3,
  GOT_INPUT_CLIENT = 4,
  PLAN_PREP_READY = 5,
  PLAN_READY = 6,
  PLAN_DONE = 7,
  TOTAL_STATES = 8
};

enum TEST2_SOURCES {
  CLIENT = 0,
  SEE_MODULE = 1,
  PLAN_MODULE = 2
};

enum TEST2_NOTIFICATION_TYPES {
  START_SEGMENTATION = 0,
  END_SEGMENTATION = 1,
  START_SQ_FITTING = 2,
  END_SQ_FITTING = 3,
  START_PLAN = 4,
  END_PLAN = 5
};


enum TEST2_MSG_SERVER_TYPE {
  MSG_PLAN_START_UPDATES = 0,
  MSG_PLAN_STOP_UPDATES = 1,
  MSG_SEE_GRAB_IMG = 2,
  MSG_PLAN_PREP_REQUEST = 3,
  MSG_SEND_OBJ_COMMAND = 4,
  MSG_START_PLAN_COMMAND = 5,
  MSG_GO_BACK_PLAN_COMMAND = 6,
  TOTAL_MSG_TYPES = 7
};



enum TEST2_MSG_PROCESS_TYPES {
  START_MSG = 0,
  RESET_MSG = 1,
  GO_BACK_MSG = 2,
  CONNECTED_MSG = 3,
  RCV_IMAGE_MSG = 4,
  RCV_INPUT_MSG = 5,
  PLAN_PREP_DONE_MSG = 6,
  SENT_OBJ_MSG = 7,
  PLAN_DONE_MSG = 8
};

enum TEST2_ACTION_TYPES {
  NO_ACTION = 0,
  SEND_IMAGE_REQUEST = 1,
  SEND_INPUT_REQUEST = 2,
  SEND_UPDATE_REQUEST = 3,
  SEND_PREP_REQUEST_PLAN = 4,
  SEND_OBJ_COMMAND = 5,
  START_PLANNING_COMMAND = 6
};
