#!/bin/bash

CHANNELS="ref-left state-left"
CHANNELS="$CHANNELS ref-right state-right"
CHANNELS="$CHANNELS sdhref-left sdhstate-left"
CHANNELS="$CHANNELS sdhref-right sdhstate-right"
CHANNELS="$CHANNELS gatekeeper_msg_chan"
CHANNELS="$CHANNELS tactile-left tactile-right"

# Trajectory channels
TRAJ_CHANNELS="bimanual_chan bimanual_hand_chan"

# Workstations 
PLANNING_HOST="powell"
CONTROL_HOST="calvin" 

#*****************
# DEFINITIONS
#*****************

# SocketCAN interfaces
CAN_L=can0 # Left arm
CAN_R=can1 # Right arm
CAN_T=can2 # Torso

# esdCAN interfaces
CAN_SDH_L=0 # Left hand
CAN_SDH_R=1 # Right hand

# RS-232 Serial ports for tactile info
SERIAL_L=2 # Left Hand
SERIAL_R=0 # Right Hand


# Check where SNS is located
if test -z $SNS; then
    if test -x /home/ana/local/etc/init.d/sns; then
	SNS=/home/ana/local/etc/init.d/sns
    elif test -x /usr/local/etc/init.d/sns; then
	SNS=/usr/local/etc/init.d/sns
    elif test -x /etc/init.d/sns; then
	SNS=/etc/init.d/sns
    else 
	echo "[ERROR] Could not find SNS program"
	exit 1
    fi
fi

#**************
# FUNCTIONS
#**************

# Make channels
crichton_ach_mk() {
    for c in $CHANNELS; do
	ach mk -1 -o 666 $c
    done

    # For trajectories
    for c in $TRAJ_CHANNELS; do
        ach mk -m 7 -n 3000 -1 -o 666 $c
    done  
}

# Remove channels
crichton_ach_rm() {
    for c in $CHANNELS; do
	sudo ach rm $c
    done

    for c in $TRAJ_CHANNELS; do
	sudo ach rm $c
    done
}


# SNS service start
crichton_start_sns() {
    snslogd_is_running=`pgrep snslogd`
	echo "snslogd (if exists) has pid:: ${snslogd_is_running}"
    
    if test -z $snslogd_is_running; then
	echo "\t * Starting SNS service"
	$SNS start
    else 
	echo "\t * SNS already is running"
    fi
}

# Start : Create channels + start SNS + run daemons
crichton_start() {
    crichton_ach_mk

    # Pull arm/hand states
    $SNS run -d push_state_left -- \
    achd -d push $PLANNING_HOST state-left 	

    $SNS run -d push_state_right -- \
    achd -d push $PLANNING_HOST state-right	

   $SNS run -d push_sdhstate_left -- \
    achd -d push $PLANNING_HOST sdhstate-left 	
   
   $SNS run -d push_sdhstate_right -- \
    achd -d push $PLANNING_HOST sdhstate-right	

   $SNS run -d pull_bimanual_chan -- \
    achd -d pull $PLANNING_HOST bimanual_chan

    $SNS run -d pull_bimanual_hand_chan -- \
     achd -d pull $PLANNING_HOST bimanual_hand_chan


   $SNS run -d push_gatekeeper_msg_chan -- \
    achd  push $PLANNING_HOST gatekeeper_msg_chan

   # Push tactile information
   $SNS run -d push_tactile_left -- \
   achd push $PLANNING_HOST tactile-left

   $SNS run -d push_tactile_right -- \
   achd push $PLANNING_HOST tactile-right

    # Run daemons
    $SNS run -d -r lwa-left -- \
    can402 -f $CAN_L -R 1 -C 0 -n 3 -n 4 -n 5 -n 6 -n 7 -n 8 -n 9 -c ref-left -s state-left 

     $SNS run  -d -r sdh-left -- \
     sdhiod -b $CAN_SDH_L -c sdhref-left -s sdhstate-left

#     $SNS run -d -r contact-left -- \
#     dsad_full -c tactile-left -s $SERIAL_L

     $SNS run -d -r lwa-right -- \
     can402 -f $CAN_R -R 1 -C 0 -n 3 -n 4 -n 5 -n 6 -n 7 -n 8 -n 9 -c ref-right -s state-right    

     $SNS run  -d -r sdh-right -- \
     sdhiod -b $CAN_SDH_R -c sdhref-right -s sdhstate-right

#     $SNS run -d -r contact-right -- \
#     dsad_full -c tactile-right -s $SERIAL_R
}

# Expunge: Remove temporal folders for log
crichton_expunge() {

  NAMES="lwa-left sdh-left contact-left"
  NAMES="$NAMES lwa-right sdh-right contact-right"
  NAMES="$NAMES pull_bimanual_chan pull_bimanual_hand_chan"
  NAMES="$NAMES push_state_left push_state_right"
  NAMES="$NAMES push_sdhstate_left push_sdhstate_right"
  NAMES="$NAMES push_tactile_left push_tactile_right"
  NAMES="$NAMES push_gatekeeper_msg_chan"
 	
  SNS_FOLDERS_RM=""

  # Create folder names
  for i in $NAMES; do
    folder_tmp="/var/tmp/sns/$i"
    folder_run="/var/run/sns/$i"
    SNS_FOLDERS_RM="$SNS_FOLDERS_RM $folder_tmp $folder_run"
  done
                                                           
   sudo rm -rf -R $1 $SNS_FOLDERS_RM
}


# Stop: Stop daemons and programs
crichton_stop() {
    $SNS kill lwa-left
    $SNS kill sdh-left
    $SNS kill contact-left

    $SNS kill lwa-right
    $SNS kill sdh-right
    $SNS kill contact-right


    $SNS kill push_state_left
    $SNS kill push_state_right

    $SNS kill push_sdhstate_left
    $SNS kill push_sdhstate_right

    $SNS kill push_tactile_left
    $SNS kill push_tactile_right

    $SNS kill pull_bimanual_chan
    $SNS kill pull_bimanual_hand_chan
    $SNS kill push_gatekeeper_msg_chan

    crichton_ach_rm
}

# Change ownerships of SNS temporal files
crichton_steal() {

  NAMES="lwa-left sdh-left contact-left"
  NAMES="$NAMES lwa-right sdh-right contact-right"
  NAMES="$NAMES pull_bimanual_chan pull_bimanual_hand_chan"
  NAMES="$NAMES push_state_left push_state_right"
  NAMES="$NAMES push_sdhstate_left push_sdhstate_right"
  NAMES="$NAMES push_tactile_left push_tactile_right"
  NAMES="$NAMES push_gatekeeper_msg_chan"
 	
  SNS_FOLDERS_STEAL=""

  # Create folder names
  for i in $NAMES; do
    folder_tmp="/var/tmp/sns/$i"
    folder_run="/var/run/sns/$i"
    SNS_FOLDERS_STEAL="$SNS_FOLDERS_STEAL $folder_tmp $folder_run"
  done
                                                           
  chown -R $1 $SNS_FOLDERS_STEAL
  chgrp -R $1 $SNS_FOLDERS_STEAL
}

#***************************
# SET SCRIPT OPTIONS
#***************************
case "$1" in
    start)
	crichton_start
	;;
    stop)
	crichton_stop
	;;
    rm) 
	crichton_ach_rm
	;;
    mk)
	crichton_ach_mk
	;;
    steal)
	shift
	crichton_steal $@
	;;
    expunge)
	crichton_expunge
	;;
	  zero)
  	echo "-- Sending zero velocity to left arm"
		snsref ref-left -d -- 0 0 0 0 0 0 0 
		sleep 2
  	echo "-- Sending zero velocity to right arm"
  	snsref ref-right -d -- 0 0 0 0 0 0 0 
  	sleep 2
	;;	
    *)
	echo "[ERROR] Invalid command. Options are start/stop/rm/mk/steal/zero NEW_OWNER/expunge"
	exit 1
	;;
esac

