#!/bin/sh

# Find SNS
if test -x ~/local/etc/init.d/sns; then
   SNS=~/local/etc/init.d/sns
elif test -x /usr/local/etc/init.d/sns; then
   SNS=/usr/local/etc/init.d/sns
elif test -x /etc/init.d/sns; then
   SNS=/etc/init.d/sns
else 
   echo "Could not find SNS program"
   exit 1
fi



#*****************************
# Workstations
#*****************************
PLANNING_HOST="powell" 
CONTROL_HOST="calvin"  


#==================================
# Call functions on input argument
#==================================
case "$1" in

	#**********************
	# START
	#**********************
	start)

	    
	    # Pull arm/hand states
#	    $SNS run -d -r pull_state_left -- \
			  achd -d pull $CONTROL_HOST state-left 	

#	    $SNS run -d -r pull_sdhstate_left -- \
	      achd -d pull $CONTROL_HOST sdhstate-left		   

#	    $SNS run -d -r pull_state_right -- \
	      achd -d pull $CONTROL_HOST state-right 	 
      
#	    $SNS run -d -r pull_sdhstate_left -- \
        achd -d pull $CONTROL_HOST sdhstate-right		
	    
	    # Push arm/hand ref
#	    $SNS run -d -r push_bimanual_hand_chan -- \
	      achd -d push $CONTROL_HOST bimanual_hand_chan	
	    
#	    $SNS run -d -r push_bimanual_chan -- \
        achd -d push $CONTROL_HOST bimanual_chan
	    ;;
	
	#**********************
	# STOP
	#**********************
	stop)
	    $SNS kill pull_state_left
      $SNS kill pull_sdhstate_left
      $SNS kill pull_state_right
      $SNS kill pull_sdhstate_right
      $SNS kill push_bimanual_hand_chan
      $SNS kill push_bimanual_chan
	    ;;
	
	#**********************
	# EXPUNGE
	#**********************
	expunge)
	    
	    sudo rm -rf /var/tmp/sns/state-left	
	    sudo rm -rf /var/run/sns/state-left
	    
	    sudo rm -rf /var/tmp/sns/sdhstate-left	
	    sudo rm -rf /var/run/sns/sdhstate-left
	    
	    sudo rm -rf /var/tmp/sns/state-right	
	    sudo rm -rf /var/run/sns/state-right
	    
	    sudo rm -rf /var/tmp/sns/sdhstate-right	
	    sudo rm -rf /var/run/sns/sdhstate-right
	    
	    echo "Expunging!"
	    
	    ;;
	
	#**********************
	# ALL ELSE
	#**********************
	*)
	    echo "Invalid command"	
	    exit 1
	    ;;
esac




