#!/bin/sh

#*****************
# DEFINITIONS
#*****************

CHANNELS="ref-left state-left"
CHANNELS="$CHANNELS ref-right state-right"
CHANNELS="$CHANNELS gripref-left gripstate-left"
CHANNELS="$CHANNELS gripref-right gripstate-right"

# Trajectory channels
TRAJ_CHANNELS="bimanual_chan bimanual_hand_chan"

# Workstations 
PLANNING_HOST="powell"
CONTROL_HOST="baley" 

#*******************************
# Check where SNS is located
#*******************************

# Find SNS
if test -x ~/local/etc/init.d/sns; then
   SNS=~/local/etc/init.d/sns
elif test -x /usr/local/etc/init.d/sns; then
   SNS=/usr/local/etc/init.d/sns
elif test -x /etc/init.d/sns; then
   SNS=/etc/init.d/sns
else 
   echo "Could not find SNS program"
   exit 1
fi

#**************
# FUNCTIONS
#**************

# Make channels
alita_ach_mk() {
    for c in $CHANNELS; do
	ach mk -1 -o 666 $c
    done

    # For trajectories
    for c in $TRAJ_CHANNELS; do
        ach mk -m 7 -n 3000 -1 -o 666 $c
    done  
}

# Remove channels
alita_ach_rm() {
    for c in $CHANNELS; do
	ach rm $c
    done

    for c in $TRAJ_CHANNELS; do
	ach rm $c
    done
}

#***************************
# SET SCRIPT OPTIONS
#***************************
case "$1" in

	#**********************
	# START
	#**********************
	mk)
        alita_ach_mk
	    ;;
	
	#**********************
	# STOP
	#**********************
	rm)
        alita_ach_rm
	    ;;
		
	#**********************
	# ALL ELSE
	#**********************
	*)
	    echo "[ERROR] Invalid command. Options are mk/rm"	
	    exit 1
	    ;;
esac




