
#pragma once

enum PAP_STATES {
  LISTENING_STATE = 0,
  SEEING_STATE = 1,
  PLANNING_STATE = 2,
  EXECUTING_STATE = 3
};

enum PAP_MESSAGES {
  NULL_MSG = 0,
  START_SOLUTION_MSG = 1,
  START_SEEING_MSG = 2,
  FINISHED_SEEING_MSG = 3,
  START_PLANNING_MSG = 4,
  FINISHED_PLANNING_MSG = 5,
  START_EXECUTING_MSG = 6,
  FINISHED_EXECUTING_MSG = 7,
  START_SOLUTION_BACK_MSG = 8,
  RESET_UI_MSG = 9,
  INFO_MSG = 10
};
